inherit_gem:
  rubocop-rails-omakase: rubocop.yml

plugins:
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys
  EnforcedShorthandSyntax: always

Layout/IndentationConsistency:
  Enabled: true

Layout/IndentationWidth:
  Enabled: true

Minitest/MultipleAssertions:
  Enabled: true
